server:
  port: 8080

spring:
  # Kafka 配置项，对应 KafkaProperties 配置类
  kafka:
    bootstrap-servers: 47.96.190.164:9092
    producer:
      acks: 1 # 0-不应答。1-leader 应答。all-所有 leader 和 follower 应答。
      retries: 0 # 发送失败时，重试发送的次数
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # 消息的 key 的序列化
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # 消息的 value 的序列化
      # value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer # 消息的 value 的序列化
    consumer:
      client-id: consumer1
      group-id: group1
      auto-offset-reset: earliest # 设置消费者分组最初的消费进度为 earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      # value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    listener:
      concurrency: 1
      ack-mode: manual_immediate
      # 消费监听接口监听的主题不存在时，默认会报错。所以通过设置为 false ，解决报错
      missing-topics-fatal: false
  influx:
    url: http://47.96.190.164:8086
    username: root
    database: test_db
    password: lfx@influxdb666
    retention: myPolicy:365d
kafka:
  topic:
    my-topic1: my-topic1
    my-topic2: my-topic2

logging:
  level:
    org:
      springframework:
        kafka: ERROR # spring-kafka
      apache:
        kafka: ERROR # kafka