version: "3"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PWD}/mount/portainer/data:/data:rw"
  influxdb:
    image: influxdb:1.7.8
    container_name: influxdb
    ports:
      - '8086:8086'
    volumes:
      - "${PWD}/mount/influxdb:/root/influxdb/data"
    environment:
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=lfx@influxdb666
      - INFLUXDB_DB=test

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    volumes:
      - "./data:/data"
    ports:
      - "2182:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://45.77.178.28:9092
      KAFKA_CREATE_TOPICS: "test-topic:3:0"   #kafka启动后初始化一个有2个partition(分区)0个副本名叫kafeidou的topic
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    volumes:
      - "./kafka-logs:/kafka"
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=45.77.178.28:9092
    depends_on:
      - kafka