version: '3.0'
services:
  zookeeper:
    image: wurstmeister/zookeeper   # 镜像
    container_name: zookeeper
    ports:
      - "2181:2181"                 # 对外暴露的端口号
    networks:
      - myNetwork
  kafka:
    image: wurstmeister/kafka       # 镜像
    container_name: kafka
    volumes:
      - /etc/localtime:/etc/localtime # 挂载位置（kafka镜像和宿主机器之间时间保持一直）
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 47.96.190.164         # 修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181       # 卡夫卡运行是基于zookeeper的
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: 120
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DELETE_RETENTION_MS: 1000
    networks:
      - myNetwork
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9093:8080"
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
  kafka-manager:
    image: sheepkiller/kafka-manager                # 镜像：开源的web管理kafka集群的界面
    container_name: kafka-manager
    environment:
      ZK_HOSTS: 47.96.190.164                         # 修改:宿主机IP
    ports:
      - "9001:9000"                                 # 暴露端口 9000这个端口冲突太多
    depends_on:
      - zookeeper
    networks:
      - myNetwork
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - "9002:9000"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/var/run/docker.sock:/var/run/docker.sock"  # admin 111222333444555
    networks:
      - myNetwork
  influxdb:
    image: influxdb:1.7.8
    container_name: influxdb
    ports:
      - '8086:8086'
    volumes:
      - "${PWD}/influxdb:/root/influxdb/data"
    environment:
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=lfx@influxdb666
      - INFLUXDB_DB=test
    networks:
      - myNetwork
networks:
  myNetwork: